rjeriomenko/GoalGetters

README.md

Update background and overview in README

Background

---

README.md
thoughts.txt

refine MVPs & Functionality section

Readme functionality

---

README.md

Update Technologies & Technical Challenges

Update technologies and challenges

---

README.md

Update group members and work breakdown

Update group members and work breakdown

---

backend/APPFLOW.md

Create document with user navigation flow

Create document with user navigation flow

---

frontend/src/components/NavBar/NavBar.js
frontend/src/components/SessionForms/SessionForm.css
frontend/src/index.css

Add CSS reset and session form styling

Frontend setup structuring

---

frontend/public/index.html
frontend/src/components/NavBar/NavBar.css
frontend/src/components/SessionForms/LoginForm.js
frontend/src/components/SessionForms/SessionForm.css
frontend/src/components/SessionForms/SignupForm.js
frontend/src/index.css

Frontend auth styling

---

frontend/src/components/FeedPosts/FeedPostEditable.css
frontend/src/components/FeedPosts/FeedPostEditable.js
frontend/src/components/FeedPosts/GoalCreate.js
frontend/src/components/FloatingMenu/FloatingMenu.js
frontend/src/components/SessionForms/SessionForm.css
frontend/src/context/Modal.css
frontend/src/context/Modal.js
frontend/src/index.js

FeedPostEditable & ancillary changes:
GoalCreate.js - <FeedPostBlock> -> <FeedPostEditable>
FloatMenu.js - minor change
SessionForm.css - minor change
index.js - Modal Provider wrapper, minor change
FeedPostEditable .js .css - new component

Frontend add exercise entry form

---

frontend/src/components/FeedPosts/GoalCreate.js

Test GoalCreate dispatch, modify dispatch to add session user id

Update GoalCreate to include id in dispatch

---

backend/app.js
backend/models/Goal.js
backend/models/User.js
backend/routes/api/feed.js
backend/routes/api/users.js
backend/validations/goals.js

created feed backend, updated validations for goals, modified other relevant backend files

create feed route, update goals validations

---

frontend/src/store/goals.js

correct GoalReducer comment

---

frontend/src/App.js
frontend/src/components/FeedPosts/GoalCreate.js
frontend/src/components/Goals/GoalEdit.js
frontend/src/components/Goals/GoalIndex.css
frontend/src/components/Goals/GoalIndex.js
frontend/src/components/Goals/GoalIndexItem.js
frontend/src/components/NavBar/NavBar.js

Create goal edit form, add redirect paths to goal create and goal edit

Update goal show

---

frontend/src/components/FeedPosts/GoalCreate.js
frontend/src/components/Goals/GoalEdit.js
frontend/src/components/Goals/GoalIndex.css
frontend/src/components/Goals/GoalIndex.js

Add delete button to goals, comment out dependencies array in goal index (console go crazyy)

Add delete button goals

---

backend/routes/api/users.js
frontend/src/store/exerciseEntries.js
frontend/src/store/goals.js

Untested exerciseEventsReducer

Finish creating exerciseEventsReducer thunks, selectors, and reducer

---

backend/routes/api/users.js
frontend/src/components/Test/Test.js
frontend/src/store/exerciseEntries.js

Finish testing exerciseEvents thunks

Finish testing exerciseEvents thunks

---

frontend/src/components/Exercise/ExerciseEventForm.css
frontend/src/components/Exercise/ExerciseEventForm.js
frontend/src/components/Goals/GoalEdit.js
frontend/src/components/NavBar/NavBar.js
frontend/src/store/exerciseEntries.js

Add create functionality to exercise event and fix css

Update exercise entry form

---

frontend/src/components/Exercise/ExerciseEventForm.js
frontend/src/components/FloatingMenu/FloatingMenu.js
frontend/src/components/Goals/GoalEdit.js

Update Exercise event form to redirect upon submit for modal

Exercise form update

---

backend/seeders/seeds.js

Data vis seeds

---

backend/models/Exercise.js
backend/routes/api/exercises.js
frontend/src/components/Test/Test.js
frontend/src/store/errors.js
frontend/src/store/exercises.js
frontend/src/store/store.js

Exercise reducer

---

backend/routes/api/users.js
frontend/src/components/Profile/DataVis.css
frontend/src/components/Profile/DataVis.js
frontend/src/components/Profile/Profile.js

finessing needs to be done on the graph logic, but it late, me tired

GRAPH IS GRAPHINGGGG, but will need modified for dynamic inputs sadface

---

frontend/src/store/goals.js

Update createGoal reducer for real this time

---

frontend/src/components/FeedPosts/GoalCreate.js

Update dispatch to create goal

---

frontend/src/components/FeedPosts/Feed.js
frontend/src/components/Test/Test.js
frontend/src/store/goals.js

Update removeGoals reducer

---

Page Functions + Schema.txt
backend/routes/api/users.js
frontend/src/components/Exercise/ExerciseEventForm.js
frontend/src/components/Goals/GoalEdit.js
frontend/src/components/Goals/GoalIndex.js
frontend/src/components/Profile/Profile.js
frontend/src/components/SessionForms/LoginForm.js
frontend/src/components/SessionForms/SignupForm.js
frontend/src/components/Test/Test.js
frontend/src/store/errors.js
frontend/src/store/goals.js
frontend/src/store/store.js
frontend/src/store/users.js

Create fetchUser and fetchUsers

Create fetchUser and fetchUsers

---

frontend/src/store/exerciseEntries.js

update updateworkout reducer

---

frontend/src/components/FeedPosts/Feed.js
frontend/src/components/FeedPosts/FeedPostGoal.js
frontend/src/components/FeedPosts/FeedPostWorkout.js
frontend/src/components/Profile/Profile.js
frontend/src/components/Test/Test.js
frontend/src/store/exerciseEntries.js
frontend/src/store/feedPosts.js
frontend/src/store/goals.js
frontend/src/store/users.js

Setup preemptive reducers

---

frontend/src/components/FeedPosts/Feed.js
frontend/src/components/FeedPosts/FeedPostExerciseEntry.js
frontend/src/components/FeedPosts/FeedPostGoal.js
frontend/src/components/FeedPosts/FeedPostWorkout.js
frontend/src/components/NavBar/NavBar.css
frontend/src/components/NavBar/NavBar.js

finally fix feed goals

---

backend/routes/api/goals.js
frontend/src/components/Exercise/ExerciseEventForm.js
frontend/src/components/FeedPosts/Feed.js
frontend/src/components/FeedPosts/FeedPost.css
frontend/src/components/FeedPosts/FeedPostGoal.js
frontend/src/components/FeedPosts/FeedPostWorkout.js
frontend/src/components/FloatingMenu/FloatingMenu.css
frontend/src/components/FloatingMenu/FloatingMenu.js
frontend/src/components/Footer/Footer.js
frontend/src/components/Goals/GoalCreate.css
frontend/src/components/Goals/GoalCreate.js
frontend/src/components/Goals/GoalIndex.css
frontend/src/components/Goals/GoalIndex.js
frontend/src/components/Goals/GoalIndexItem.css
frontend/src/components/Goals/GoalIndexItem.js
frontend/src/components/NavBar/NavBar.js
frontend/src/store/errors.js
frontend/src/store/store.js
frontend/src/store/users.js

Update goal page

---

frontend/src/components/Exercise/ExerciseEventForm.js
frontend/src/components/FloatingMenu/FloatingMenu.js
frontend/src/store/exerciseEntries.js

add dispatch for createExercise into form
-- need to update floating menu logic

Update exercise event form

---

frontend/src/components/Goals/GoalIndex.css
frontend/src/components/Goals/GoalIndex.js

Goal complete button

---

backend/routes/api/exerciseEntries.js
backend/routes/api/goals.js
frontend/src/components/Feed/Feed.js
frontend/src/components/Feed/FeedPostGoal.js
frontend/src/components/Feed/FeedPostWorkout.js
frontend/src/components/Feed/FollowNavBar.js
frontend/src/components/FloatingMenu/FloatingMenu.js
frontend/src/components/Goals/GoalIndex.js
frontend/src/components/Goals/GoalIndexItem.js
frontend/src/components/LandingPage/LandingPage.js
frontend/src/components/NavBar/NavBar.js

Fix broken feed images

---

frontend/src/components/NavBar/NavBar.css
frontend/src/components/NavBar/NavBar.js

add dropdown arrow

---

frontend/src/components/Feed/Feed.js

feed null id issue fixed

---

frontend/src/components/Exercise/ExerciseEventForm.css

Fix fuzzy dropdown position
